spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://192.168.0.101:3308/hiringbell
    username: root
    password: live@Bottomhalf_001

    #    local instance
#    url: jdbc:mysql://localhost:3306/hiringbell
#    username: root
#    password: Marghub12@

    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 622966386962-it5k2ko2s8h1l07cs3ls4n19492ej7eo.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka